### ISSUE TITLE
Snapcopy in newton

### ISSUE THREAD

**Issue by ManriqueGarcia** [emc-openstack/vnx-direct-driver#10]
Hi, I have newton and I can add snapcopy=true in metadata for default like in liberty

**Comment by peter-wangxu** [comment]
Were you asking if snapcopy is available for newton? if yes, the answer is true.

Thanks
Peter

**Comment by ManriqueGarcia** [comment]
Hi Peter, thanks for you answer.

The question is about how I can configure snapcopy, before newton I
configure snapcopy in volume type

cinder type-update set copytype:snap=true

but in newto this not works fine. I need configure snap copy in the
creation of snapshot and volume with cinder --metadata snapcopy=true but is
not persistent.

I have commvault for backups and commvault do
cinder snapshot-create <volume-id>
cinder create --snapshot-id <snaphost-id>

How I could do persistent for all volume types snapcopy=true

Thanks, best regards

**Comment by peter-wangxu** [comment]
Hi @ManriqueGarcia 
Configuring the snapcopy via volume type had been removed since `Mitaka`. the new snapcopy is controlled over metadada. 

For you case, you can simply&quickly adopt the new feature as follows:

```console
cinder snapshot-create <volume-id>
cinder create --snapshot-id <snaphost-id>--metadata snapcopy=True
```
You have better control over the behavior of cloning without touching the volume type.

Checkout [newton snapcopy](https://docs.openstack.org/newton/config-reference/block-storage/drivers/emc-vnx-driver.html#snap-copy) for details.

Thanks
Peter

**Comment by ManriqueGarcia** [comment]
Hi, I need change snapcopy=false

I try to change it but when I create a volume I have error

**Comment by peter-wangxu** [comment]
Any error msg?

**Comment by ManriqueGarcia** [comment]
Yes, my apologies, I forget it

 DEBUG oslo_service.service [req-fb181d58-a0e4-4f9e-a433-20115855c646 - - -
- -] publish_errors                 = False log_opt_values
/usr/lib/python2.7/site-packages/oslo_config/cfg.py:2622


Thanks

**Comment by ManriqueGarcia** [comment]
Sorry, I restart openstack volume service and now I don't have error but
the metadata volume is still snapcopy=false

I think also I need to create snapshot with metadata snapcopy=true

Thanks

**Comment by peter-wangxu** [comment]
BTW, you should always apply the metadata when creating volume (either from volume or from snapshot) instead of creating snapshot.

Thanks
Peter

**Comment by ManriqueGarcia** [comment]
Thanks, I'll talk whit commvault to use metadata in his commands

Thanks, for all

**Comment by peter-wangxu** [comment]
Closing it for now, Please reopen it when necessary
