### ISSUE TITLE
Question: how to configure multiple SP backends

### ISSUE THREAD

**Issue by Lirt** [emc-openstack/vnx-direct-driver#9]
Hello EMC,

older releases of openstack (liberty, mitaka) had configuration parameter `san_secondary_ip`, which specified IP address to second SP (usually B). 

This parameter is not available in openstack newton and ocata and now I am confused if I should configure parameter `san_ip` multiple times, or if `san_ip` accepts an array (IP addresses separated by comma). 

Either way it would be nice to update documentation about configuring multiple SPs.

I followed this documentation: https://docs.openstack.org/ocata/config-reference/block-storage/drivers/emc-vnx-driver.html

**Comment by peter-wangxu** [comment]
@Lirt 
It's as designed.

Prior to newton, the HA mechanisim(IP switching) is done by driver, since newton, the HA had been moved to an library `storops` so the `san_secondary_ip` is not needed in cinder.conf, it's acquired by storops automatically when driver starts up. In a word, newton(and after) driver only needs the `san_ip`, and the HA is maintained within `storops`.

**Comment by Lirt** [comment]
Ok, thank you for information.

I want to ask one more question, recently we had primary SP (A) in faulty state and in cinder log I found, that it wanted to connect to IP address of this faulty SP (A) and since it couldn't, cinder didn't load properly. 

Secondary SP (B) was fine, but I didn't find any information about trying to connect to it in cinder log. So does it mean that when `storops` is handling HA and the `san_ip` address (SP A in my case) is down, the HA will not work, because it can not ask `san_ip` for second (SP B) IP address?

**Comment by peter-wangxu** [comment]
storops will connect the `san_ip` and gets  IP of another SP during driver startup.
the driver will refuse to startup if the `san_ip` is unavailble.

currently, the HA only takes place after a successful driver startup.

when restart the cinder driver, our suggestion is to make sure  the `san_ip` to an available SP.

Thanks
Peter

**Comment by Lirt** [comment]
Okay, thank you for explanation. I am closing this issue.
